/**
 * Textos de interfaz centralizados (DECISIONS 2026-09-14: un solo idioma
 * activo, pero los textos viven en un módulo y no sueltos en cada componente).
 * Voz y terminología: docs/arquitectura/marca.md §5. Los textos de carga,
 * error y vacío son los de docs/arquitectura/user-flow.md §7, literales.
 *
 * Fuente de la verdad de los datos: los Excel del owner (DECISIONS
 * 2026-10-06). Las pantallas son de solo lectura y dicen dónde se corrige.
 */

export const EXCEL = {
  paquetes: "Excel de paquetes",
  proveedores: "Excel de proveedores",
  tramosTours: "tramos de los tours (data/tramos-con-proveedor.csv)",
} as const;

export const TEXTOS = {
  app: {
    producto: "Reservas de Catálogo",
    logoAlt: "HI Travel",
  },
  navegacion: {
    titulo: "Secciones",
    catalogo: "Catálogo",
    proveedores: "Proveedores",
    pendientes: "Pendientes",
  },
  comunes: {
    reintentar: "Reintentar",
    sinDato: "—",
    soloLectura: "Solo lectura. Los datos se corrigen en los Excel y se vuelven a importar.",
  },
  catalogo: {
    titulo: "Catálogo de productos",
    buscar: "Buscar por código o nombre",
    buscarPlaceholder: "Ej. CHB31 u overland",
    error: "No pudimos cargar el catálogo.",
    vacio: "El catálogo está vacío. Sin productos cargados, las reservas no se pueden emparejar.",
    accionVacio: "Cargar productos",
    ayudaVacio: "Los productos se cargan con el importador, desde el Excel de paquetes.",
    sinResultados: "Ningún producto coincide con la búsqueda.",
    cargando: "Cargando el catálogo",
    columnas: {
      codigo: "Código",
      nombre: "Nombre",
      ciudades: "Ciudades",
      proveedores: "Proveedores",
      actualizado: "Última edición",
    },
    tour: "Tour",
    pendientes: (n: number) => (n === 1 ? "1 pendiente" : `${n} pendientes`),
    cantidad: (n: number) => (n === 1 ? "1 producto" : `${n} productos`),
  },
  producto: {
    error: "No pudimos abrir este producto.",
    volver: "Volver al catálogo",
    cargando: "Cargando el producto",
    tipoTour: "Tour compuesto",
    tipoPaquete: "Paquete",
    ciudades: "Ciudades",
    destino: "Destino",
    actualizado: "Última edición",
    codigos: "Códigos de agencia",
    sinCodigos: "Sin códigos de agencia cargados.",
    alojamiento: "Alojamiento por nivel",
    otrosServicios: "Servicios",
    serviciosDelTour: "Servicios propios del tour",
    itinerario: "Itinerario día por día",
    duracionEtiqueta: "Duración",
    duracion: (dias: number) => `${dias} días`,
    sinProveedores:
      "Este producto no tiene proveedores asociados. No se le podrán armar pedidos.",
    noOfrecido: "No ofrecido",
    sinNivel: "Sin nivel",
    opcionN: (n: number) => `${n}ª opción`,
    bookingSupplier: "Pedido a",
    serviceProvider: "Presta",
    sinMailCargado: "sin mail cargado",
    origenExcel: (fila: number) => `${EXCEL.paquetes}, fila ${fila}`,
    origenTramos: `Cargado de los ${EXCEL.tramosTours}`,
    dia: (n: number) => `Día ${n}`,
    noches: (n: number) => (n === 1 ? "1 noche" : `${n} noches`),
    transferIn: "Transfer de llegada",
    transferOut: "Transfer de salida",
    busNocturno: "Bus nocturno",
    busDiurno: "Bus diurno",
    tramoExterno: "Tramo externo pendiente de emitir",
    tramoEmite: "Pasaje que emite HI Travel. Sin proveedor.",
    esTourEnlace: "Es un tour. Ver su itinerario completo.",
    tipos: {
      alojamiento: "Alojamiento",
      excursion: "Excursión",
      traslado: "Traslado",
      bus: "Bus",
      crucero: "Crucero",
      otro: "Otro",
    },
  },
  estadoServicio: {
    con_mail: "Con mail",
    whatsapp: "Por WhatsApp (pedido a mano)",
    manual: "Manual en sistema propio",
    sin_resolver: "Sin resolver",
    opcional: "Opcional",
    motivoNoEnDirectorio: (nombre: string) =>
      `«${nombre}» no está en el directorio. Se carga en el ${EXCEL.proveedores}.`,
    motivoSinProveedor: `El servicio no tiene proveedor. Se completa en el ${EXCEL.paquetes}.`,
    motivoSinContacto: (nombre: string) =>
      `«${nombre}» no tiene mail ni WhatsApp. Se completa en el ${EXCEL.proveedores}.`,
    manualEn: (sistema: string) => `Se reserva a mano en ${sistema}.`,
  },
  directorio: {
    titulo: "Directorio de proveedores",
    error: "No pudimos cargar el directorio.",
    vacio: "No hay proveedores cargados. Se necesitan para poder mandarles los pedidos.",
    accionVacio: "Agregar proveedor",
    ayudaVacio: "Los proveedores se cargan con el importador, desde el Excel de proveedores.",
    cargando: "Cargando el directorio",
    filtroSinMail: "Proveedores sin mail",
    buscar: "Buscar proveedor",
    buscarPlaceholder: "Nombre o ciudad",
    sinResultados: "Ningún proveedor coincide con la búsqueda.",
    sinMail: "Sin mail",
    columnas: {
      nombre: "Nombre",
      mail: "Mail de contacto",
      canal: "Canal",
      otros: "Teléfono / otros datos",
      ciudad: "Ciudad",
      productos: "Productos",
    },
    canales: { mail: "Mail", whatsapp: "WhatsApp", ninguno: "Sin canal" },
    cantidad: (n: number) => (n === 1 ? "1 proveedor" : `${n} proveedores`),
  },
  proveedor: {
    error: "No pudimos abrir este proveedor.",
    volver: "Volver al directorio",
    cargando: "Cargando el proveedor",
    mails: "Mails",
    canal: "Canal",
    telefono: "Teléfono",
    aclaraciones: "Aclaraciones",
    ciudad: "Ciudad",
    productos: "Productos donde aparece",
    sinProductos: "No aparece en ningún producto cargado.",
    rol: {
      booking_supplier: "Se le pide la reserva",
      service_provider: "Presta el servicio",
      ambos: "Presta y se le pide",
    },
    avisoSinMail: `Este proveedor no tiene mail cargado. Se completa en el ${EXCEL.proveedores} y se vuelve a importar.`,
    avisoWhatsapp: "Se le pide por WhatsApp, a mano: no recibe pedidos automáticos.",
  },
  pendientes: {
    titulo: "Pendientes",
    intro:
      "Lo que falta completar en los Excel para que cada servicio tenga a quién pedírselo. Después de corregir, se vuelve a importar.",
    error: "No pudimos cargar los pendientes.",
    vacio: "No hay pendientes. Todos los servicios tienen a quién pedírselos.",
    cargando: "Cargando los pendientes",
    columnas: {
      producto: "Producto",
      servicio: "Servicio",
      proveedor: "Proveedor",
      motivo: "Qué falta",
      dondeSeCorrige: "Dónde se corrige",
    },
    cantidad: (n: number) => (n === 1 ? "1 pendiente" : `${n} pendientes`),
  },
} as const;
